apiVersion: "apps/v1" # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simpleapp-mysql
  labels:
    app: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpleapp
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: simpleapp
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: "3306"
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: "apps/v1" # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpleapp
        tier: frontend
    spec:
      containers:
      - image: acrdevopse.azurecr.io/simple-app
        name: simpleapp
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: simpleapp.settings.production
        - name: MYSQL_DATABASE
          value: simpleapp
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: simpleapp-mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 80
          name: simpleapp
